import type { ScenarioKiosk } from "../types";

export const bobaKiosk: ScenarioKiosk = {
  enabled: true,
  storage: {
    receipts: "boba-kiosk-receipts",
    language: "boba-kiosk-language",
  },
  defaultLanguage: "en",
  defaultOptionIds: {
    drink: "milk-tea",
    size: "medium",
    sweetness: "half-sugar",
    ice: "less-ice",
  },
  currency: "元",
  pageSize: 8,
  completeLine: "訂單完成，請取飲料。",
  speechPinyin: {
    aiyu: "ài yù",
    agar: "hán tiān",
    "black-tea": "hóng chá",
    "black-tea-latte": "hóng chá ná tiě",
    boba: "bō bà",
    "boba-milk-tea": "bō bà nǎi chá",
    "brown-sugar-boba-milk": "hēi táng zhēn zhū xiān nǎi",
    "coconut-jelly": "yē guǒ",
    "grass-jelly": "xiān cǎo",
    "grass-jelly-milk-tea": "xiān cǎo nǎi dòng",
    "green-tea": "lǜ chá",
    "half-sugar": "bàn táng",
    hot: "rè",
    large: "dà bēi",
    "lemon-black-tea": "níng méng hóng chá",
    "less-ice": "shǎo bīng",
    "less-sugar": "shǎo táng",
    "light-ice": "wēi bīng",
    "light-sugar": "wēi táng",
    "matcha-latte": "mǒ chá ná tiě",
    medium: "zhōng bēi",
    "milk-foam": "nǎi gài",
    "milk-tea": "nǎi chá",
    "mini-pearl": "xiǎo zhēn zhū",
    "no-ice": "qù bīng",
    "no-sugar": "wú táng",
    "oolong-milk-tea": "wū lóng nǎi chá",
    "oolong-tea": "wū lóng chá",
    "orange-green-tea": "liǔ chéng lǜ chá",
    "passion-green-tea": "bǎi xiāng lǜ chá",
    pearl: "zhēn zhū",
    "pearl-milk-tea": "zhēn zhū nǎi chá",
    pudding: "bù dīng",
    "pudding-milk-tea": "bù dīng nǎi chá",
    "regular-ice": "zhèng cháng bīng",
    "regular-sugar": "zhèng cháng táng",
    sijichun: "sì jì chūn qīng chá",
    "taro-ball": "yù yuán",
    "taro-milk": "yù tóu xiān nǎi",
    "tieguanyin-milk-tea": "tiě guān yīn nǎi chá",
    "wintermelon-lemon": "dōng guā níng méng",
    "yakult-green-tea": "duō duō lǜ chá",
  },
  englishOptionLabels: {
    aiyu: "Aiyu Jelly",
    agar: "Agar",
    "black-tea": "Black Tea",
    "black-tea-latte": "Black Tea Latte",
    boba: "Boba",
    "boba-milk-tea": "Boba Milk Tea",
    "brown-sugar-boba-milk": "Brown Sugar Boba Milk",
    "coconut-jelly": "Coconut Jelly",
    "grass-jelly": "Grass Jelly",
    "grass-jelly-milk-tea": "Grass Jelly Milk Tea",
    "green-tea": "Green Tea",
    "half-sugar": "Half Sugar",
    hot: "Hot",
    large: "Large",
    "lemon-black-tea": "Lemon Black Tea",
    "less-ice": "Less Ice",
    "less-sugar": "Less Sugar",
    "light-ice": "Light Ice",
    "light-sugar": "Light Sugar",
    "matcha-latte": "Matcha Latte",
    medium: "Medium",
    "milk-foam": "Milk Foam",
    "milk-tea": "Milk Tea",
    "mini-pearl": "Mini Pearls",
    "no-ice": "No Ice",
    "no-sugar": "No Sugar",
    "oolong-milk-tea": "Oolong Milk Tea",
    "oolong-tea": "Oolong Tea",
    "orange-green-tea": "Orange Green Tea",
    "passion-green-tea": "Passion Green Tea",
    pearl: "Pearls",
    "pearl-milk-tea": "Pearl Milk Tea",
    pudding: "Pudding",
    "pudding-milk-tea": "Pudding Milk Tea",
    "regular-ice": "Regular Ice",
    "regular-sugar": "Regular Sugar",
    sijichun: "Sijichun Tea",
    "taro-ball": "Taro Balls",
    "taro-milk": "Taro Milk",
    "tieguanyin-milk-tea": "Tieguanyin Milk Tea",
    "wintermelon-lemon": "Wintermelon Lemon",
    "yakult-green-tea": "Yakult Green Tea",
  },
  copy: {
    add: { en: "Add to cart", zh: "加入購物車" },
    addMore: { en: "Add more", zh: "繼續加點" },
    back: { en: "Back", zh: "返回" },
    cart: { en: "Cart", zh: "購物車" },
    checkout: { en: "Checkout", zh: "結帳" },
    chooseDrink: { en: "Choose a drink", zh: "選擇飲料" },
    clear: { en: "Clear", zh: "清空" },
    done: { en: "Done", zh: "完成" },
    emptyCart: { en: "Your cart is empty", zh: "購物車是空的" },
    ice: { en: "Ice", zh: "冰塊" },
    lineTotal: { en: "Item total", zh: "小計" },
    newOrder: { en: "New order", zh: "新訂單" },
    next: { en: "Next", zh: "下一頁" },
    previous: { en: "Previous", zh: "上一頁" },
    publicMode: { en: "Public Mode", zh: "公開模式" },
    receipt: { en: "Receipt", zh: "收據" },
    remove: { en: "Remove", zh: "移除" },
    size: { en: "Size", zh: "杯型" },
    start: { en: "Start order", zh: "開始點餐" },
    sweetness: { en: "Sweetness", zh: "甜度" },
    tapToOrder: { en: "Tap to order", zh: "點一下開始點餐" },
    title: { en: "Boba Kiosk", zh: "珍奶自助點餐" },
    toppings: { en: "Toppings", zh: "加料" },
    total: { en: "Total", zh: "總計" },
    viewCart: { en: "View cart", zh: "查看購物車" },
  },
};
