import type { ScenarioScene } from "../types";

export const bobaScene: ScenarioScene = {
  assets: {
    worldUrl: "/assets/world/cozy-boba-shop.spz",
    colliderUrl: "/assets/world/cozy-anime-boba-shop-collider.glb",
    cashierUrl: "/assets/characters/aki/aki-cashier.glb",
    customerUrl: "/assets/characters/universal-base/Superhero_Male_FullBody.gltf",
  },
  loading: {
    preparing: "Preparing Boba Tea Shop...",
    world: "Loading Boba Tea Shop...",
    worldReady: "World ready",
    initializingWorld: "Initializing world...",
    cashier: "Loading cashier...",
    cashierReady: "Cashier ready",
    movement: "Preparing movement...",
    movementReady: "Movement ready",
    fallbackScene: "World unavailable; continuing.",
    ready: "Ready",
  },
  receipt: {
    title: "珍奶快打",
    arcadeSubtitle: "挑戰收據",
    openSubtitle: "自由練習收據",
    scoreUnit: "分",
    scoreParts: [
      { key: "correctness", label: "正確", max: 60 },
      { key: "politeness", label: "禮貌", max: 15 },
      { key: "smoothness", label: "順暢", max: 15 },
      { key: "clarity", label: "清楚", max: 10 },
    ],
  },
  menuBoards: [
    {
      x: -0.43,
      title: "招牌奶茶",
      subtitle: "MILK TEA",
      footer: "人氣推薦",
      rotationY: 0.025,
      palette: {
        faceTop: "#d5dfae",
        face: "#aebf80",
        faceBottom: "#738457",
        frame: "#9a7a42",
        frameDark: "#5a3b24",
        trim: "#f1e7c8",
        ink: "#302d18",
        muted: "rgba(48, 45, 24, 0.68)",
        row: "rgba(255, 245, 216, 0.36)",
        rowAlt: "rgba(255, 245, 216, 0.2)",
      },
      rows: [
        { label: "奶茶", price: "45" },
        { label: "珍珠奶茶", price: "60" },
        { label: "波霸奶茶", price: "65" },
        { label: "烏龍奶茶", price: "55" },
        { label: "黑糖珍珠鮮奶", price: "75" },
      ],
    },
    {
      x: 0,
      title: "清爽茶飲",
      subtitle: "FRUIT TEA",
      footer: "現泡茶底",
      rotationY: 0,
      palette: {
        faceTop: "#f4e9cb",
        face: "#dfca90",
        faceBottom: "#a8894f",
        frame: "#856233",
        frameDark: "#513622",
        trim: "#fff5d8",
        ink: "#2c2416",
        muted: "rgba(48, 45, 24, 0.62)",
        row: "rgba(255, 245, 216, 0.34)",
        rowAlt: "rgba(255, 245, 216, 0.18)",
      },
      rows: [
        { label: "紅茶", price: "35" },
        { label: "四季春青茶", price: "45" },
        { label: "冬瓜檸檬", price: "50" },
        { label: "百香綠茶", price: "55" },
        { label: "柳橙綠茶", price: "55" },
      ],
    },
    {
      x: 0.43,
      title: "客製選項",
      subtitle: "CUSTOM",
      footer: "慢慢說沒問題",
      rotationY: -0.025,
      palette: {
        faceTop: "#50623f",
        face: "#647c52",
        faceBottom: "#34432a",
        frame: "#7b6136",
        frameDark: "#44301f",
        trim: "#f1e7c8",
        ink: "#fff5d8",
        muted: "rgba(255, 245, 216, 0.68)",
        row: "rgba(255, 245, 216, 0.13)",
        rowAlt: "rgba(48, 45, 24, 0.22)",
      },
      rows: [
        { label: "杯型", detail: "中杯 / 大杯 +10" },
        { label: "甜度", detail: "正常 少糖 半糖 微糖 無糖" },
        { label: "冰塊", detail: "正常 少冰 微冰 去冰 熱" },
        { label: "加料", detail: "珍珠 波霸 布丁 椰果" },
      ],
    },
  ],
};
